apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: fastapi-app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s