apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets-uami
  namespace: micro-app
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    # Option A: supply the user-assigned managed identity client id
    userAssignedIdentityID: "'${UAMI_CLIENT_ID}'"
    # Option B: alternatively supply the full resource id (uncomment if you prefer)
    # userAssignedIdentityID: "/subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<uami-name>"
    keyvaultName: "peerisland-asses-kv"
    tenantId: "'${AZURE_TENANT_ID}'"
    objects: |
      array:
        - |
          objectName: django-secret-key
          objectType: secret
        - |
          objectName: allowed-hosts
          objectType: secret